package uah; // Generated by Selenium IDE

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class Test1GeneratedFromSideFile {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    Assumptions.assumeTrue(
        Boolean.parseBoolean(System.getProperty("run.selenium", "false")),
        "Skipping Selenium test: set -Drun.selenium=true to run");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void test1() {
    driver.get("https://escuelapolitecnica.uah.es/");
    driver.manage().window().setSize(new Dimension(752, 615));
    assertThat(driver.getTitle(), is("Escuela Politécnica Superior - UAH"));
    assertThat(
        driver.findElement(By.cssSelector("address")).getText(),
        is("Campus Universitario. Ctra. Madrid-Barcelona, Km. 33,600. Alcalá de Henares (Madrid)"));
    driver.findElement(By.linkText("Aula Virtual")).click();
  }
}
